CREATE DATABASE ARTISTA_OPTUS;
GO

USE ARTISTA_OPTUS;
GO

CREATE TABLE EMPRESA(
idEmpresa INT PRIMARY KEY IDENTITY(1,1),
nomeEmpresa VARCHAR(50) NOT NULL UNIQUE,
endereco VARCHAR(60) NOT NULL UNIQUE,
);
GO

CREATE TABLE ARTISTA(
idArtista INT PRIMARY KEY IDENTITY(1,1),
idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
nomeArtista VARCHAR(75) NOT NULL UNIQUE,
);
GO

CREATE TABLE ALBUM(
idAlbum INT PRIMARY KEY IDENTITY(1,1),
idArtista INT FOREIGN KEY REFERENCES ARTISTA(idArtista),
nomeAlbum VARCHAR(50) NOT NULL UNIQUE,
datalançamento DATE NOT NULL,
localizacao VARCHAR(100) NOT NULL UNIQUE,
quantidadeMinutos INT NOT NULL,
ativoVisualizacao BIT NOT NULL,
);
GO

CREATE TABLE ESTILO(
idEstilo INT PRIMARY KEY IDENTITY(1,1),
nomeEstilo VARCHAR(15) NOT NULL,
nomeEstilo1 VARCHAR(15) NOT NULL,
nomeEstilo2 VARCHAR(15) NOT NULL,
);
GO

CREATE TABLE USUARIO(
idUsuario INT PRIMARY KEY IDENTITY(1,1),
idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
nomeUsuario VARCHAR(50) NOT NULL UNIQUE,
nomeEmail VARCHAR(85) NOT NULL UNIQUE,
senha VARCHAR(25) NOT NULL,
tipoPermissao BIT NOT NULL,
);
Go

CREATE TABLE ESTILO_ALBUM(
idEstiloALbum INT PRIMARY KEY IDENTITY(1,1),
idAlbum INT FOREIGN KEY REFERENCES ALBUM(idAlbum),
idEstilo INT FOREIGN KEY REFERENCES ESTILO(idEstilo)
);