CREATE DATABASE STUDIO;
GO

USE STUDIO;
GO

CREATE TABLE EMPRESA(
idEmpresa INT PRIMARY KEY IDENTITY(1,1),
nomeEmpresa VARCHAR(50) NOT NULL UNIQUE,
endereco VARCHAR(60) NOT NULL UNIQUE,
);
GO

CREATE TABLE ARTISTA(
idArtista INT PRIMARY KEY IDENTITY(1,1),
idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
nomeArtista VARCHAR(75) NOT NULL UNIQUE,
);
GO

CREATE TABLE ALBUM(
idAlbum INT PRIMARY KEY IDENTITY(1,1),
idArtista INT FOREIGN KEY REFERENCES ARTISTA(idArtista),
nomeAlbum VARCHAR(50) NOT NULL UNIQUE,
);
GO

ALTER TABLE ALBUM ADD titulo VARCHAR(60) NOT NULL UNIQUE ----------->coloquei sem querer outra coluna titulo
ALTER TABLE ALBUM ADD datalançamento DATE NOT NULL
ALTER TABLE ALBUM ADD localizacao VARCHAR(100) NOT NULL UNIQUE
ALTER TABLE ALBUM ADD quantidadeMinutos INT NOT NULL
ALTER TABLE ALBUM ADD ativoVisualização VARCHAR(3) NOT NULL
ALTER TABLE ALBUM DROP COLUMN titulo 

CREATE TABLE CD(
idCd INT PRIMARY KEY IDENTITY(1,1),
idAlbum INT FOREIGN KEY REFERENCES ALBUM(idAlbum),
nomeCd VARCHAR(60) NOT NULL UNIQUE,
numeroCd VARCHAR(60) NOT NULL UNIQUE,
);
GO

CREATE TABLE ESTILO(
idEstilo INT PRIMARY KEY IDENTITY(1,1),
idCd INT FOREIGN KEY REFERENCES CD(idCd),
nomeEstilo VARCHAR(15) NOT NULL,
nomeEstilo1 VARCHAR(15) NOT NULL,
nomeEstilo2 VARCHAR(15) NOT NULL,
);
GO

CREATE TABLE USUARIO(
idUsuario INT PRIMARY KEY IDENTITY(1,1),
idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
nomeUsuario VARCHAR(50) NOT NULL UNIQUE,
nomeEmail VARCHAR(85) NOT NULL UNIQUE,
senha VARCHAR(25) NOT NULL,
tipoPermissao VARCHAR(13) NOT NULL, ------->Procurar depois como colocar apenas duas opçoes
);
GO