CREATE DATABASE LOCADORA;
GO 

USE LOCADORA;
GO

CREATE TABLE EMPRESA(
idEmpressa INT PRIMARY KEY IDENTITY(1,1),
nomeEmpresa VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE MARCA(
idMarca INT PRIMARY KEY IDENTITY(1,1),
nomeMarca VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE CLIENTE(
idCliente INT PRIMARY KEY IDENTITY(1,1),
nomeCliente CHAR(50) NOT NULL UNIQUE,
);
GO

ALTER TABLE CLIENTE ADD CPF CHAR(11) UNIQUE;

CREATE TABLE MODELO(
idModelo INT PRIMARY KEY IDENTITY(1,1),
idMarca INT FOREIGN KEY REFERENCES MARCA(idMarca),
nome VARCHAR(50) NOT NULL,
anoModelo DATE NOT NULL,
tamanhoModelo SMALLINT NOT NULL,
);
GO

CREATE TABLE VEICULO(
idVeiculo INT PRIMARY KEY IDENTITY(1,1),
idModelo INT FOREIGN KEY REFERENCES MODELO(idModelo),
idEmpressa INT FOREIGN KEY REFERENCES EMPRESSA(idEmpressa),
placa CHAR(7) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEL(
idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente),
dataRetirada DATE NOT NULL,
dataDevolucao DATE NOT NULL,
);
GO

