CREATE DATABASE CLINICA;
GO 

USE CLINICA;
GO

CREATE TABLE CLINICA(
idClinica INT PRIMARY KEY IDENTITY(1,1),
nomeClinica VARCHAR(50) NOT NULL UNIQUE,
endereco VARCHAR(60) NOT NULL UNIQUE,
);
GO

ALTER TABLE CLINICA ADD razaoSocial VARCHAR(75) NOT NULL

CREATE TABLE TIPO(
idTipo INT PRIMARY KEY IDENTITY(1,1),
nomeTipo VARCHAR(25) NOT NULL,
);
GO

CREATE TABLE DONO(
idDono INT PRIMARY KEY IDENTITY(1,1),
nomeDono VARCHAR(60) NOT NULL UNIQUE,
);
GO

CREATE TABLE VETERINARIO(
idVeterinario INT PRIMARY KEY IDENTITY(1,1),
idClinica INT FOREIGN KEY REFERENCES CLINICA(idClinica),
nomeVeterinario VARCHAR(50) NOT NULL UNIQUE,
especializacao VARCHAR(40) NOT NULL,
CRMV VARCHAR(5) NOT NULL
);
GO

CREATE TABLE RACA(
idRaca INT PRIMARY KEY IDENTITY(1,1),
idTipo INT FOREIGN KEY REFERENCES TIPO(idTipo),
nomeRaca VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE PET(
idPet INT PRIMARY KEY IDENTITY(1,1),
idDono INT FOREIGN KEY REFERENCES DONO(idDono),
idRaca INT FOREIGN KEY REFERENCES RACA(idRaca),
nomePet VARCHAR(30) NOT NULL UNIQUE,
nascimento DATE NOT NULL,
);
GO

CREATE TABLE CONSULTA(
idConsulta INT PRIMARY KEY IDENTITY(1,1),
idVeterinario INT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
idPet INT FOREIGN KEY REFERENCES PET(idPet),
dataHoraConsulta DATETIME NOT NULL,
descricaoConsulta VARCHAR(500) NOT NULL,
);
GO