CREATE DATABASE PCLINICS;
GO 

USE PCLINICS;
GO

CREATE TABLE CLINICA(
idClinica INT PRIMARY KEY IDENTITY(1,1),
endereco VARCHAR(60) NOT NULL UNIQUE
);
GO

CREATE TABLE PET(
idPet INT PRIMARY KEY IDENTITY(1,1),
nomePet VARCHAR(30) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
idVeterinario INT PRIMARY KEY IDENTITY(1,1),
idClinica INT FOREIGN KEY REFERENCES CLINICA(idClinica),
nomeVeterinario VARCHAR(50) NOT NULL UNIQUE,
especializacao VARCHAR(40) NOT NULL,
);
GO

CREATE TABLE CONSULTA(
idConsulta INT PRIMARY KEY IDENTITY(1,1),
idVeterinario INT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
idPet INT FOREIGN KEY REFERENCES PET(idPet),
dataHoraConsulta DATETIME NOT NULL,
);
GO

ALTER TABLE CONSULTA ADD descricaoConsulta VARCHAR(500) NOT NULL
ALTER TABLE CONSULTA ADD dataConsulta DATETIME

CREATE TABLE RACA(
idRaca INT PRIMARY KEY IDENTITY(1,1),
idPet INT FOREIGN KEY REFERENCES PET(idPet),
nomeRaca VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE TIPO(
idTipo INT PRIMARY KEY IDENTITY(1,1),
idRaca INT FOREIGN KEY REFERENCES RACA(idRaca),
nomeTipo VARCHAR(25) NOT NULL,
);
GO

CREATE TABLE DONO(
idDono INT PRIMARY KEY IDENTITY(1,1),
idPet INT FOREIGN KEY REFERENCES PET(idPet),
nomeDono VARCHAR(60) NOT NULL UNIQUE,
);
GO