CREATE DATABASE LOCADORA;
GO 

USE LOCADORA;
GO

CREATE TABLE EMPRESSA(
idEmpressa INT PRIMARY KEY IDENTITY(1,1),
nomeEmpressa VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE MARCA(
idMarca INT PRIMARY KEY IDENTITY(1,1),
nomeMarca VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE CLIENTE(
idCliente INT PRIMARY KEY IDENTITY(1,1),
nomeCliente CHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE MODELO(
idModelo INT PRIMARY KEY IDENTITY(1,1),
idMarca INT FOREIGN KEY REFERENCES MARCA(idMarca),
nome VARCHAR(50) NOT NULL,
anoModelo TINYINT IDENTITY(4,4) NOT NULL,
tamanhoModelo SMALLINT NOT NULL,
);
GO

CREATE TABLE VEICULO(
idVeiculo INT PRIMARY KEY IDENTITY(1,1),
idModelo INT FOREIGN KEY REFERENCES MODELO(idModelo),
idEmpressa INT FOREIGN KEY REFERENCES EMPRESSA(idEmpressa),
placa CHAR(7) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEL(
idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente),
preco SMALLINT NOT NULL,
modeloContrato DATE NOT NULL,
dataAluguel DATETIME NOT NULL,
);
GO

